### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by ltetrel** [neurolibre/submit#2]
Submission :
* Mechanism to trigger testing/building whenever we fork a project on neurolibre
* Automatic build from notebook to jupyter book with prebuild hook
* Github bots to handle issues
* How to manage tutorials submissions (ressource request)
* Cookie cutter template for the user/ template repo so user can fork and start from scratch if they want

**Comment by mathieuboudreau** [comment]
"How to submit" section needs an accompanying demo repo and/or links to example files (e.g. not everyone knows how to format the requirement and data_requirement files)

**Comment by mathieuboudreau** [comment]
Point #7 of that section: There is no "upload" button, it's "launch".

**Comment by mathieuboudreau** [comment]
There is point #8 twice (one of them is within #7)

**Comment by mathieuboudreau** [comment]
Point #3: We need either a requirements.txt file (and all the other one that come with it, e.g. postBuild), **or** a Dockerfile, which is the other option.

**Comment by ltetrel** [comment]
> Point #3: We need either a requirements.txt file (and all the other one that come with it, e.g. postBuild), **or** a Dockerfile, which is the other option.

based on my epexrience, we should first ask the user to try with the requirement files. If it does not work then they should try the Dockerfile, but I had some issues with the latest.

**Comment by lunebellec** [comment]
It looks like at least part of this thread has been addressed. @ltetrel maybe close this one and open separate issues if there are remaining concerns to discuss.

**Comment by ltetrel** [comment]
@pbellec I don't get what why you are saying that ? None of the points are resolved

**Comment by mathieuboudreau** [comment]
@ltetrel Can we convert these to-do items into individual Github issues so that they can be treated & assigned separately?

**Comment by mathieuboudreau** [comment]
Actually, it looks like some of them are already issues, and others are resolved, so can we close this one?

**Comment by ltetrel** [comment]
Yes I will close it
